# Generated by Django 3.1.2 on 2020-12-23 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('label', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=45, null=True, verbose_name='nickname')),
                ('firstname', models.CharField(blank=True, max_length=45, null=True, verbose_name='firstname')),
                ('lastname', models.CharField(blank=True, max_length=45, null=True, verbose_name='lastname')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/contact')),
                ('labels', models.ManyToManyField(to='label.Label')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
